spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:postgresql://localhost:5432/coding
    username: postgres
    password: yusupov2002


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

  mail:
    host: smtp.mailtrap.io
    port: 587
    username: 1ad4e3fe2f420e
    password: 1d78bc1b5ae633
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  access:
    secret: tHaX54Hwk^YMzKd@e@p7#70@!@*6d7676K8C1%T&hBnrzgqK28o
    expiration: 72000000
  refresh:
    secret: tHaX54Hwk^Ydfd()(+__$$%#%70OZ()BK8C1%T&hBnrzgqK287
    expiration: 86400000




activation:
  link:
    expiry:
      in:
        minutes: 2

    base:
      path: http://localhost:8080/api/v1/auth/activate?activation_code=%s




app:
  admin:
    email: yusupov@gmail.com
    password: root